# Data Pre-processing

#### reading data in the inputDataFrame
providing file path of car dataset and reading those data in the Pandas dataframe,
here, if there are null values, they will be converted into '?",
we have provided header name list

In [168]:
import pandas as pd
inputFilePath = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
inputDataFrame = pd.read_csv(filepath_or_buffer = inputFilePath, na_values='?', skipinitialspace=True, 
                             names  = ['buying', 'maint', 'doors','persons','lug_boot','safety', 'class'])

In [169]:
inputDataFrame.head()


buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

#### removing null values

In [170]:
nullRemovedDataFrame = inputDataFrame.dropna()

#### convert categorical data into numerical data

In [171]:
#creating a data frame which contains the object type values
objDataFrame = nullRemovedDataFrame.select_dtypes(include=['object']).copy()
nRows, nCols = objDataFrame.shape
#for all column converting object type in categoty type and assigning
#appropriate code
for myIndex in range(0,nCols):
    headerName = objDataFrame.columns[myIndex]
    objDataFrame[headerName] = objDataFrame[headerName].astype("category")
    objDataFrame[headerName] = objDataFrame[headerName].cat.codes
    #writing objectDataFrame column to its respective dataFrame column
    nullRemovedDataFrame[headerName] = objDataFrame[headerName]            
#for myIndex -ends
numericDataFrame = nullRemovedDataFrame


In [172]:
numericDataFrame.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [173]:
y = numericDataFrame[['class']]

In [174]:
y.head()

class
0      2
1      2
2      2
3      2
4      2

#### Scale the data:      
scaling data using MinMaxScaler

In [175]:
import numpy as np
#finding shape of dataframe
nRows, nCols = numericDataFrame.shape

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
numericDataFrame[numericDataFrame.columns] = scaler.fit_transform(numericDataFrame[numericDataFrame.columns])
scaledDataFrame = numericDataFrame

In [176]:
x= scaledDataFrame[['buying', 'maint', 'doors','persons','lug_boot','safety']]
x.head()

buying  maint  doors  persons  lug_boot  safety
0     1.0    1.0    0.0      0.0       1.0     0.5
1     1.0    1.0    0.0      0.0       1.0     1.0
2     1.0    1.0    0.0      0.0       1.0     0.0
3     1.0    1.0    0.0      0.0       0.5     0.5
4     1.0    1.0    0.0      0.0       0.5     1.0

In [177]:
x.head()

buying  maint  doors  persons  lug_boot  safety
0     1.0    1.0    0.0      0.0       1.0     0.5
1     1.0    1.0    0.0      0.0       1.0     1.0
2     1.0    1.0    0.0      0.0       1.0     0.0
3     1.0    1.0    0.0      0.0       0.5     0.5
4     1.0    1.0    0.0      0.0       0.5     1.0

In [178]:
y.head()

class
0      2
1      2
2      2
3      2
4      2

splitting data into training and testing - currently fitting data only on the training data to adjust the hyper parameters

In [179]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test = train_test_split(x, y, test_size = 0, random_state=10)

In [180]:
from sklearn.tree import DecisionTreeClassifier

Playing with hyper parameters of Decision tree

In [181]:
clf_decisionTree = DecisionTreeClassifier(criterion= "entropy", random_state=100, min_samples_leaf=10)

In [182]:
clf_decisionTree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=10, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [183]:
predict_decisionTree = clf_decisionTree.predict(x_train)

In [184]:
from sklearn.metrics import classification_report, confusion_matrix
print (confusion_matrix(y_train, predict_decisionTree))
print (classification_report(y_train, predict_decisionTree))

[[ 354   12   15    3]
 [   6   60    3    0]
 [  24    0 1186    0]
 [   0    4    0   61]]
             precision    recall  f1-score   support

          0       0.92      0.92      0.92       384
          1       0.79      0.87      0.83        69
          2       0.99      0.98      0.98      1210
          3       0.95      0.94      0.95        65

avg / total       0.96      0.96      0.96      1728



## Neural Network:

In [185]:
import copy
x_neural_net_train=x_train.copy()
y_neural_net_train=y_train.copy()


In [186]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(7,12,10), random_state=10, max_iter=1000)

y_neural_net_train=y_neural_net_train.values.reshape((1728,))
clf.fit(x_neural_net_train,y_neural_net_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(7, 12, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=10, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [187]:
predictions = clf.predict(x_neural_net_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_neural_net_train,predictions))
print(classification_report(y_neural_net_train,predictions))

[[ 377    0    7    0]
 [   0   69    0    0]
 [  10    0 1200    0]
 [   0    0    0   65]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.98       384
          1       1.00      1.00      1.00        69
          2       0.99      0.99      0.99      1210
          3       1.00      1.00      1.00        65

avg / total       0.99      0.99      0.99      1728



# Support Vector Machine

In [207]:
import copy
x_svm_train=x_train.copy()
y_svm_train=y_train.copy()
y_svm_train=y_svm_train.values.reshape((1728,))


In [208]:
from sklearn.svm import SVC
clf = SVC(kernel='rbf',random_state=20,C=20)
clf.fit(x_svm_train, y_svm_train) 

SVC(C=20, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=20, shrinking=True,
  tol=0.001, verbose=False)

In [209]:
predictions = clf.predict(x_svm_train)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_svm_train,predictions))
print(classification_report(y_svm_train,predictions))

[[ 357   13   11    3]
 [  15   51    0    3]
 [  24    0 1186    0]
 [   3    0    0   62]]
             precision    recall  f1-score   support

          0       0.89      0.93      0.91       384
          1       0.80      0.74      0.77        69
          2       0.99      0.98      0.99      1210
          3       0.91      0.95      0.93        65

avg / total       0.96      0.96      0.96      1728

